import {useEffect,useState} from 'react';
import {apiFetch} from '../lib/api';
import './SalesTools.css';
export default function SalesCenter(){
 const [data,setData]=useState(null),[error,setError]=useState('');
 async function load(){try{setData(await apiFetch('/api/sales/admin'));setError('');}catch(e){setError(e.message);}}
 useEffect(()=>{load();},[]);
 async function resolve(id,status){try{await apiFetch(`/api/sales/admin/${id}`,{method:'PATCH',body:JSON.stringify({status})});await load();}catch(e){setError(e.message);}}
 return <section><div className="dashboard-heading"><div><p className="eyebrow">Sales</p><h1>Builds worth following up.</h1></div><button className="btn-outline" onClick={load}>Refresh</button></div>{error&&<p role="alert">{error}</p>}{data&&<><p>Saved-link emails: {data.email?'Connected':'Not configured'}. Recovery reminders: {data.recovery?'Enabled for opted-in shoppers':'Paused — email sender and business mailing address required'}.</p><p>Last 30 days. Starts are unique browser sessions; orders come from confirmed order statuses.</p><div className="dashboard-stats">{[...data.events.map(e=>[e.event.replaceAll('_',' '),e.count]),['Saved builds',data.counts.find(l=>l.kind==='build')?.count||0],['Saved checkouts',data.counts.find(l=>l.kind==='checkout')?.count||0],['Purchases from saved links',data.recovered.orders],['Revenue from saved links',`$${Number(data.recovered.revenue).toFixed(2)}`],['Paid orders',data.orders.purchases],['Order revenue',`$${Number(data.orders.revenue).toFixed(2)}`]].map(([label,value])=><div key={label} className="dashboard-stat"><small>{label}</small><h2>{value}</h2></div>)}</div><h2>Fitment inbox</h2><div className="sales-inbox">{!data.leads.some(l=>l.kind==='fitment')&&<p>No fitment inquiries yet.</p>}{data.leads.filter(l=>l.kind==='fitment').map(l=><article className="sales-lead" key={l.id}><strong>{l.payload.brand} {l.payload.year} {l.payload.model}</strong><p>{l.email} · {new Date(l.created_at).toLocaleDateString()} · {l.status}</p>{/^https:\/\//.test(l.payload.photoUrl)&&<a href={l.payload.photoUrl} target="_blank" rel="noreferrer">View wheel photo ↗</a>}<p><a href={`mailto:${encodeURIComponent(l.email)}?subject=Your%20steering%20wheel%20fitment%20request`}>Reply by email</a></p><button className="btn-outline" onClick={()=>resolve(l.id,l.status==='open'?'resolved':'open')}>{l.status==='open'?'Mark resolved':'Reopen'}</button></article>)}</div><h2>Recent saved builds and checkouts</h2>{data.leads.filter(l=>l.kind!=='fitment').map(l=><p key={l.id}>{l.email} · {l.kind} · {new Date(l.created_at).toLocaleDateString()} · {l.stage} reminders sent</p>)}</>}</section>;
}
